# Generated by Django 4.1.4 on 2022-12-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('measurement', models.CharField(max_length=50)),
                ('total_onion', models.IntegerField()),
                ('minimum_rate', models.IntegerField()),
                ('maximum_rate', models.IntegerField()),
                ('row_date', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
