# Generated by Django 4.1.4 on 2022-12-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops_rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onionrate',
            name='row_date',
        ),
        migrations.AlterField(
            model_name='onionrate',
            name='date',
            field=models.DateField(),
        ),
    ]
